import "@/styles/globals.css";


export const metadata = {
  title: "Top Social Media Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
         <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
    rel="stylesheet"
/>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
