import "@/styles/globals.css";
import SmoothScrollProvider from "../components/SmoothScrollProvider";

export const metadata = {
  title: "Top Social Media Agency | Creative Agency in US",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body>
        {/* <SmoothScrollProvider> */}
          {children}
        {/* </SmoothScrollProvider> */}
      </body>
    </html>
  );
}